// Shared schemes data — used by all Vercel serverless functions
export const schemes = [
  {
    id: '1',
    name: 'PM Kisan Samman Nidhi',
    category: 'Agriculture',
    deadline: '2025-07-31',
    description: 'Financial support of \u20b96,000/year to small and marginal farmer families across India.',
    eligibility: { maxIncome: 200000, targetGroups: ['Farmer', 'Any'], states: ['All'] },
    details: 'Under PM-KISAN, income support of \u20b96000/year in three equal installments of \u20b92000 every four months is provided to all land holding farmer families.',
    checklist: ['Must own cultivable land', 'Indian citizen', 'Annual income below \u20b92 Lakhs', 'Not a government employee'],
    documents: ['Aadhaar Card', 'Land Records', 'Bank Passbook', 'Mobile Number'],
    apply_url: 'https://pmkisan.gov.in/'
  },
  {
    id: '2',
    name: 'PM Awas Yojana (Urban)',
    category: 'Housing',
    deadline: '2025-09-30',
    description: 'Affordable housing for urban poor with interest subsidy up to \u20b92.67 lakhs on home loans.',
    eligibility: { maxIncome: 1800000, targetGroups: ['Any'], states: ['All'] },
    details: 'PMAY provides central assistance to urban local bodies for providing houses to all eligible families.',
    checklist: ['Indian citizen', 'No pucca house in family', 'Income below \u20b918 LPA for MIG-II', 'First-time home buyer'],
    documents: ['Aadhaar Card', 'Income Certificate', 'Property Documents', 'Bank Statement'],
    apply_url: 'https://pmaymis.gov.in/'
  },
  {
    id: '3',
    name: 'Pradhan Mantri Mudra Yojana',
    category: 'Business',
    deadline: '2025-12-31',
    description: 'Collateral-free loans up to \u20b910 lakhs for non-corporate, non-farm small/micro enterprises.',
    eligibility: { maxIncome: 1000000, targetGroups: ['Entrepreneur', 'Any'], states: ['All'] },
    details: 'MUDRA provides micro-finance under Shishu (up to \u20b950K), Kishor (up to \u20b95L), and Tarun (up to \u20b910L).',
    checklist: ['Age 18-65', 'Run or start a small business', 'No defaulter on any bank loans', 'Business plan ready'],
    documents: ['Aadhaar & PAN Card', 'Business Plan', 'Proof of Business', 'Bank Statement (6 months)'],
    apply_url: 'https://www.mudra.org.in/'
  },
  {
    id: '4',
    name: 'Beti Bachao Beti Padhao',
    category: 'Education',
    deadline: '2025-08-15',
    description: "Sukanya Samriddhi savings scheme with 8.2% interest rate to secure a girl child's future.",
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'A small savings scheme for girl children. Minimum \u20b9250/year; maximum \u20b91.5 lakh/year. Tax benefits under Section 80C.',
    checklist: ['Girl child below 10 years of age', 'Guardian must be Indian citizen', 'One account per girl child'],
    documents: ['Birth Certificate of Girl Child', 'Aadhaar of Parent/Guardian', 'Address Proof'],
    apply_url: 'https://www.india.gov.in/spotlight/beti-bachao-beti-padhao-yojna'
  },
  {
    id: '5',
    name: 'Ayushman Bharat PM-JAY',
    category: 'Health',
    deadline: '2025-10-31',
    description: 'Health coverage of \u20b95 lakh per family per year for secondary and tertiary hospitalization.',
    eligibility: { maxIncome: 100000, targetGroups: ['Any'], states: ['All'] },
    details: 'PM-JAY provides health insurance of \u20b95 lakh per family per year for over 12 crore poor and vulnerable families.',
    checklist: ['Socially-economically backward family', 'No daily wage earner earning over \u20b910,000/month', 'Not covered by CGHS or state scheme'],
    documents: ['Aadhaar Card', 'Ration Card', 'Income Certificate', 'E-card from Ayushman Portal'],
    apply_url: 'https://pmjay.gov.in/'
  },
  {
    id: '6',
    name: 'PM Scholarship Scheme',
    category: 'Education',
    deadline: '2025-10-15',
    description: 'Scholarship for wards of Ex-servicemen pursuing professional degrees - up to \u20b93,000/month.',
    eligibility: { maxIncome: 600000, targetGroups: ['Student', 'Any'], states: ['All'] },
    details: '\u20b92,500/month for boys and \u20b93,000/month for girls pursuing first professional degrees. Minimum 60% marks required.',
    checklist: ['Ward of Ex-serviceman/Coast Guard', 'First year of professional degree', 'Minimum 60% in Class 12', 'Family income below \u20b96 LPA'],
    documents: ['Aadhaar Card', 'Ex-Serviceman Certificate', 'Marksheet of Class 12', 'Admission Letter'],
    apply_url: 'https://ksb.gov.in/'
  },
  {
    id: '7',
    name: 'PM Ujjwala Yojana',
    category: 'Health',
    deadline: '2025-11-30',
    description: 'Free LPG connections to women from BPL households to replace polluting chulhas.',
    eligibility: { maxIncome: 100000, targetGroups: ['Any'], states: ['All'] },
    details: 'PMUY provides free LPG connections to adult women from BPL families, covering connection cost, first refill, and hotplate.',
    checklist: ['Adult woman (18+ years)', 'Belong to BPL household', 'No existing LPG connection in household', 'Aadhaar-linked bank account'],
    documents: ['Aadhaar Card', 'BPL Ration Card', 'Bank Passbook', 'Passport-size Photo'],
    apply_url: 'https://pmuy.gov.in/'
  },
  {
    id: '8',
    name: 'Atal Pension Yojana',
    category: 'Business',
    deadline: '2025-12-31',
    description: 'Guaranteed pension of \u20b91,000-\u20b95,000/month for workers in the unorganised sector after age 60.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'APY is a government-backed pension scheme for citizens aged 18-40. Monthly contribution ranges from \u20b942 to \u20b91,454.',
    checklist: ['Age between 18-40 years', 'Must have savings bank account', 'Not an income-tax payer', 'Not a member of any statutory social security scheme'],
    documents: ['Aadhaar Card', 'Bank Passbook', 'Mobile Number'],
    apply_url: 'https://npscra.nsdl.co.in/scheme-details.php'
  },
  {
    id: '9',
    name: 'PM Jan Dhan Yojana',
    category: 'Business',
    deadline: '2025-12-31',
    description: 'Zero-balance bank accounts with RuPay debit card and \u20b92 lakh accident insurance for all.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'PMJDY ensures access to banking, savings, credit, insurance and pension. Includes \u20b910,000 overdraft and \u20b92 lakh RuPay accident insurance.',
    checklist: ['Indian citizen (any age)', 'No existing bank account in family', 'Valid address proof available'],
    documents: ['Aadhaar Card', 'Voter ID or Passport', 'Address Proof', 'Passport-size Photo'],
    apply_url: 'https://pmjdy.gov.in/'
  },
  {
    id: '10',
    name: 'National Scholarship Portal (NSP)',
    category: 'Education',
    deadline: '2025-10-31',
    description: 'Central hub for 50+ government scholarships for students from Class 1 to PhD level.',
    eligibility: { maxIncome: 800000, targetGroups: ['Student', 'Any'], states: ['All'] },
    details: 'NSP offers pre-matric and post-matric scholarships to SC/ST/OBC/Minority students. Amounts range from \u20b91,000 to \u20b920,000/year.',
    checklist: ['Must be studying in a recognized institution', 'Family income below \u20b98 LPA', 'Must belong to eligible category (SC/ST/OBC/Minority)', 'Minimum 50% marks in previous exam'],
    documents: ['Aadhaar Card', 'Income Certificate', 'Caste Certificate', 'Bank Passbook', 'Bonafide Certificate'],
    apply_url: 'https://scholarships.gov.in/'
  },
  {
    id: '11',
    name: 'PM Fasal Bima Yojana',
    category: 'Agriculture',
    deadline: '2025-07-15',
    description: 'Crop insurance with very low premium (1.5%-5%) protecting farmers from natural disasters.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Farmer', 'Any'], states: ['All'] },
    details: 'PMFBY provides financial support for crop loss due to natural disasters. Premium: 1.5% Rabi, 2% Kharif, 5% commercial crops.',
    checklist: ['Must be a farmer (owner or tenant)', 'Sown the notified crop in notified area', 'Apply before the cut-off date for the season'],
    documents: ['Aadhaar Card', 'Land records (Khasra/Khatauni)', 'Sowing Certificate', 'Bank Passbook'],
    apply_url: 'https://pmfby.gov.in/'
  },
  {
    id: '12',
    name: 'Startup India Initiative',
    category: 'Business',
    deadline: '2025-12-31',
    description: '80% tax rebate, fast IPR filing, and seed funding access for registered startups.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Entrepreneur', 'Any'], states: ['All'] },
    details: 'Startup India provides 3-year tax exemption, simplified compliance, and access to \u20b910,000 crore Fund of Funds.',
    checklist: ['Business incorporated as Pvt Ltd or LLP', 'Less than 10 years since incorporation', 'Annual turnover below \u20b9100 crore', 'Working towards innovation/scalable business model'],
    documents: ['Incorporation Certificate', 'PAN Card', 'Director/Partner Aadhaar', 'Business Pitch Deck'],
    apply_url: 'https://www.startupindia.gov.in/'
  },
  {
    id: '13',
    name: 'PM Kaushal Vikas Yojana',
    category: 'Education',
    deadline: '2025-09-30',
    description: 'Free skill training and \u20b98,000 reward on certification in 300+ trades for Indian youth.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Student', 'Unemployed', 'Any'], states: ['All'] },
    details: 'PMKVY offers short-term skill training in electronics, construction, retail, IT. Certified candidates receive \u20b98,000 and job placement support.',
    checklist: ['Indian citizen aged 15-45 years', 'School/college dropout or looking for better job', 'No existing skill certificate in same domain'],
    documents: ['Aadhaar Card', 'Educational Certificates', 'Bank Passbook', 'Passport-size Photo'],
    apply_url: 'https://www.pmkvyofficial.org/'
  },
  {
    id: '14',
    name: 'E-Shram Card Scheme',
    category: 'Business',
    deadline: '2025-12-31',
    description: 'National database for unorganised workers with \u20b92 lakh accident insurance and welfare benefits.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'E-Shram registers unorganised sector workers and provides \u20b92 lakh accident insurance plus priority access to welfare schemes.',
    checklist: ['Age 16-59 years', 'Working in unorganised sector', 'Not a member of EPFO/ESIC', 'Not an income tax payer'],
    documents: ['Aadhaar Card', 'Bank Account linked to Aadhaar', 'Mobile Number (linked to Aadhaar)'],
    apply_url: 'https://eshram.gov.in/'
  },
  {
    id: '15',
    name: 'PM SVANidhi (Street Vendor Loan)',
    category: 'Business',
    deadline: '2025-08-31',
    description: 'Working capital loans starting at \u20b910,000 for street vendors affected by COVID-19.',
    eligibility: { maxIncome: 500000, targetGroups: ['Entrepreneur', 'Self-employed', 'Any'], states: ['All'] },
    details: 'PM SVANidhi provides collateral-free loans of \u20b910,000 (1st), \u20b920,000 (2nd), and \u20b950,000 (3rd). Timely repayment earns 7% interest subsidy.',
    checklist: ['Must be a street vendor', 'Possess vending certificate/letter from ULB', 'Working prior to March 24, 2020'],
    documents: ['Aadhaar Card', 'Vendor Certificate or ULB Letter', 'Bank Passbook', 'Passport-size Photo'],
    apply_url: 'https://pmsvanidhi.mohua.gov.in/'
  },
  {
    id: '16',
    name: 'Jal Jeevan Mission',
    category: 'Housing',
    deadline: '2025-11-30',
    description: 'Tap water connection to every rural household in India under Har Ghar Jal.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'JJM provides functional household tap connections of 55 litres per person per day to every rural household.',
    checklist: ['Must be a rural household', 'No existing piped water connection', 'Indian citizen', 'Register through Gram Panchayat'],
    documents: ['Aadhaar Card', 'Address Proof', 'Ration Card'],
    apply_url: 'https://jaljeevanmission.gov.in/'
  },
  {
    id: '17',
    name: 'Pradhan Mantri Suraksha Bima Yojana',
    category: 'Health',
    deadline: '2025-05-31',
    description: 'Accidental death & disability insurance of \u20b92 lakh for just \u20b920/year premium.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'PMSBY offers \u20b92 lakh for accidental death or total disability and \u20b91 lakh for partial disability at a yearly premium of only \u20b920.',
    checklist: ['Age 18-70 years', 'Active savings bank account', 'Consent for auto-debit of \u20b920/year'],
    documents: ['Aadhaar Card', 'Bank Passbook', 'Mobile Number'],
    apply_url: 'https://jansuraksha.gov.in/'
  },
  {
    id: '18',
    name: 'PM Matru Vandana Yojana',
    category: 'Women & Child',
    deadline: '2025-12-31',
    description: 'Cash benefit of \u20b95,000 in instalments for pregnant & lactating mothers for their first child.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'PMMVY provides \u20b95,000 in three installments: \u20b91,000 on pregnancy registration, \u20b92,000 on ANC check-up, and \u20b92,000 after birth registration.',
    checklist: ['Pregnant or lactating woman', 'First child only (for general category)', 'Age 19 years or above', 'Register at the nearest AWC/health facility'],
    documents: ['Aadhaar Card', 'MCP Card', 'Bank Passbook', 'Mobile Number'],
    apply_url: 'https://wcd.nic.in/schemes/pradhan-mantri-matru-vandana-yojana'
  },
  {
    id: '19',
    name: 'Sukanya Samriddhi Yojana',
    category: 'Women & Child',
    deadline: '2025-03-31',
    description: 'High-interest savings scheme for girl child with 8.2% p.a. and full tax exemption.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'SSY offers one of the highest interest rates among small savings schemes. Deposits between \u20b9250 and \u20b91.5 lakh/year. Matures when girl turns 21.',
    checklist: ['Girl child below 10 years', 'Indian citizen', 'One account per girl child', 'Maximum two accounts per family'],
    documents: ['Birth Certificate of Girl Child', 'Aadhaar of Parent/Guardian', 'Address Proof', 'Passport-size Photo'],
    apply_url: 'https://www.nsiindia.gov.in/'
  },
  {
    id: '20',
    name: 'PM Jeevan Jyoti Bima Yojana',
    category: 'Finance',
    deadline: '2025-05-31',
    description: 'Life insurance cover of \u20b92 lakh for just \u20b9436/year for citizens aged 18\u201350.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'PMJJBY provides renewable one-year life insurance cover of \u20b92 lakh on death due to any cause. Premium is auto-debited from bank account.',
    checklist: ['Age 18-50 years', 'Active savings bank account', 'Consent for auto-debit of \u20b9436/year', 'Aadhaar-linked bank account preferred'],
    documents: ['Aadhaar Card', 'Bank Passbook', 'Mobile Number'],
    apply_url: 'https://jansuraksha.gov.in/'
  },
  {
    id: '21',
    name: 'Kisan Credit Card (KCC)',
    category: 'Finance',
    deadline: '2025-06-30',
    description: 'Flexible credit up to \u20b93 lakh at 4% interest for farmers for crop and allied activities.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Farmer', 'Any'], states: ['All'] },
    details: 'KCC provides short-term credit for crop cultivation, post-harvest expenses, and allied activities. Interest subvention brings effective rate to 4% for timely repayment.',
    checklist: ['Must be a farmer (owner/tenant/sharecropper)', 'Valid land records', 'No existing KCC from another bank', 'Age 18-75 years'],
    documents: ['Aadhaar Card', 'Land Records', 'Bank Passbook', 'Passport-size Photo'],
    apply_url: 'https://www.nabard.org/'
  },
  {
    id: '22',
    name: 'Poshan Abhiyaan',
    category: 'Women & Child',
    deadline: '2025-12-31',
    description: 'Nutrition mission to reduce stunting, wasting and anaemia among children under 6 and pregnant women.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['All'] },
    details: 'POSHAN 2.0 targets reduction of stunting by 2%, wasting by 2%, and anaemia by 3% per year. Provides supplementary nutrition through Anganwadi centres.',
    checklist: ['Children aged 0-6 years', 'Pregnant and lactating mothers', 'Adolescent girls (11-14 years)', 'Register at nearest Anganwadi centre'],
    documents: ['Aadhaar Card', 'Birth Certificate (for children)', 'MCP Card (for mothers)'],
    apply_url: 'https://poshanabhiyaan.gov.in/'
  },
  {
    id: '23',
    name: 'Stand Up India',
    category: 'Finance',
    deadline: '2025-12-31',
    description: 'Bank loans between \u20b910 lakh and \u20b91 crore for SC/ST and women entrepreneurs.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Entrepreneur', 'Any'], states: ['All'] },
    details: 'Stand Up India facilitates bank loans for setting up greenfield enterprises in manufacturing, services, or trading sector for SC/ST and women borrowers.',
    checklist: ['SC/ST or woman entrepreneur', 'Age 18+ years', 'First-time enterprise (greenfield)', 'Not a defaulter with any bank/financial institution'],
    documents: ['Aadhaar & PAN Card', 'Business Plan', 'Caste Certificate (for SC/ST)', 'Bank Statement (6 months)'],
    apply_url: 'https://www.standupmitra.in/'
  },
  // ── Rajasthan State Schemes ────────────────────────────────────────────────
  {
    id: 'rj1',
    name: 'Mukhyamantri Chiranjeevi Swasthya Bima Yojana',
    category: 'Health',
    deadline: '2025-12-31',
    description: 'Free health insurance up to \u20b925 lakh per year for every family in Rajasthan.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['Rajasthan'] },
    details: 'Rajasthan government provides cashless treatment up to \u20b925 lakh/year at empanelled hospitals. Covers 1,576+ medical packages including surgery, ICU, and OPD.',
    checklist: ['Permanent resident of Rajasthan', 'Jan Aadhaar card required', 'Register at nearest e-Mitra kiosk', 'All families eligible regardless of income'],
    documents: ['Jan Aadhaar Card', 'Aadhaar Card', 'Residence Proof'],
    apply_url: 'https://chiranjeevi.rajasthan.gov.in/'
  },
  {
    id: 'rj2',
    name: 'Rajasthan Kisan Karj Mafi Yojana',
    category: 'Agriculture',
    deadline: '2025-12-31',
    description: 'Loan waiver up to \u20b92 lakh for small and marginal farmers of Rajasthan.',
    eligibility: { maxIncome: 200000, targetGroups: ['Farmer', 'Any'], states: ['Rajasthan'] },
    details: 'Rajasthan government waives crop loans up to \u20b92 lakh for small and marginal farmers who have taken loans from cooperative banks and land development banks.',
    checklist: ['Small or marginal farmer in Rajasthan', 'Loan taken from cooperative/land development bank', 'Land holding below 2 hectares', 'Rajasthan domicile'],
    documents: ['Jan Aadhaar Card', 'Land Records (Khasra/Khatauni)', 'Bank Loan Documents', 'Aadhaar Card'],
    apply_url: 'https://rajkisan.rajasthan.gov.in/'
  },
  {
    id: 'rj3',
    name: 'Indira Gandhi Shahri Rozgar Guarantee Yojana',
    category: 'Business',
    deadline: '2025-12-31',
    description: 'Guaranteed 100 days of employment per year for urban households in Rajasthan.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Unemployed', 'Any'], states: ['Rajasthan'] },
    details: 'Urban MGNREGA for Rajasthan — guarantees 100 days of wage employment to adult members of urban households willing to do unskilled manual work at \u20b9259/day.',
    checklist: ['Resident of urban area in Rajasthan', 'Age 18 years or above', 'Willing to do unskilled manual work', 'Jan Aadhaar card required'],
    documents: ['Jan Aadhaar Card', 'Aadhaar Card', 'Urban Residence Proof', 'Bank Passbook'],
    apply_url: 'https://irgyurban.rajasthan.gov.in/'
  },
  {
    id: 'rj4',
    name: 'Rajasthan Free Scooty Yojana (Devnarayan / Kali Bai)',
    category: 'Education',
    deadline: '2025-09-30',
    description: 'Free scooty for meritorious girl students from SC/ST/OBC/Minority communities in Rajasthan.',
    eligibility: { maxIncome: 250000, targetGroups: ['Student', 'Any'], states: ['Rajasthan'] },
    details: 'Rajasthan government distributes free scooties to girl students who scored 65%+ in Class 12 and are enrolled in college. Covers SC/ST/OBC/Minority/EWS categories.',
    checklist: ['Girl student in Rajasthan', 'Scored 65% or above in Class 12', 'Enrolled in college/university', 'Family income below \u20b92.5 lakh/year', 'SC/ST/OBC/Minority/EWS category'],
    documents: ['Class 12 Marksheet', 'College Enrollment Certificate', 'Caste Certificate', 'Income Certificate', 'Jan Aadhaar Card', 'Aadhaar Card'],
    apply_url: 'https://hte.rajasthan.gov.in/'
  },
  {
    id: 'rj5',
    name: 'Palanhar Yojana Rajasthan',
    category: 'Women & Child',
    deadline: '2025-12-31',
    description: 'Monthly financial support for orphaned and destitute children in Rajasthan up to age 18.',
    eligibility: { maxIncome: 120000, targetGroups: ['Any'], states: ['Rajasthan'] },
    details: 'Rajasthan provides \u20b9500/month for children aged 0-6 years and \u20b91,000/month for children aged 6-18 years who are orphaned, have disabled parents, or are from destitute families.',
    checklist: ['Child resident of Rajasthan', 'Orphaned or parent disabled/imprisoned/destitute', 'Age below 18 years', 'Family income below \u20b91.2 lakh/year', 'Palanhar (guardian) must be from same community'],
    documents: ['Birth Certificate', 'Aadhaar Card', 'Jan Aadhaar Card', 'Proof of orphan/destitute status', 'Bank Passbook of Palanhar'],
    apply_url: 'https://sje.rajasthan.gov.in/schemes/Palanhar.html'
  },
  {
    id: 'rj6',
    name: 'Rajasthan Gramin Olympic Khel',
    category: 'Education',
    deadline: '2025-08-31',
    description: 'State-funded rural sports competition for youth in Rajasthan across 8 sports disciplines.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Student', 'Any'], states: ['Rajasthan'] },
    details: 'Rajasthan government organizes rural Olympics at gram panchayat, block, district and state levels. Covers kabaddi, volleyball, hockey, football, athletics, kho-kho, tennis ball cricket, and shooting ball.',
    checklist: ['Resident of rural Rajasthan', 'Age 6 years and above', 'Register through gram panchayat', 'No prior professional sports contract'],
    documents: ['Aadhaar Card', 'Jan Aadhaar Card', 'Age Proof', 'Residence Certificate'],
    apply_url: 'https://rajasthanolympic.rajasthan.gov.in/'
  },
  {
    id: 'rj7',
    name: 'Mukhyamantri Rajshri Yojana',
    category: 'Women & Child',
    deadline: '2025-12-31',
    description: '\u20b950,000 financial benefit in 6 instalments for girl children born in Rajasthan after June 2016.',
    eligibility: { maxIncome: 999999999, targetGroups: ['Any'], states: ['Rajasthan'] },
    details: 'Rajasthan provides \u20b950,000 total in 6 instalments: \u20b92,500 at birth, \u20b92,500 at 1 year, \u20b94,000 at Class 1, \u20b95,000 at Class 6, \u20b911,000 at Class 10, \u20b925,000 at Class 12.',
    checklist: ['Girl child born on or after 1 June 2016', 'Birth in government hospital', 'Rajasthan domicile', 'Jan Aadhaar card of mother required'],
    documents: ['Birth Certificate', 'Jan Aadhaar Card of Mother', 'Aadhaar Card', 'Bank Passbook', 'School Enrollment Certificate (for later instalments)'],
    apply_url: 'https://wcd.rajasthan.gov.in/'
  },
  {
    id: 'rj8',
    name: 'Rajasthan Vishwakarma Kamgar Kalyan Yojana',
    category: 'Business',
    deadline: '2025-12-31',
    description: 'Financial assistance up to \u20b95,000 for tools and equipment to artisans and self-employed workers in Rajasthan.',
    eligibility: { maxIncome: 200000, targetGroups: ['Self-employed', 'Entrepreneur', 'Any'], states: ['Rajasthan'] },
    details: 'Rajasthan provides \u20b95,000 for purchase of tools/equipment to artisans, handicraft workers, and self-employed individuals from SC/ST/OBC/Minority/EWS categories.',
    checklist: ['Rajasthan resident', 'Artisan or self-employed worker', 'Age 18-40 years', 'SC/ST/OBC/Minority/EWS category', 'Family income below \u20b92 lakh/year'],
    documents: ['Jan Aadhaar Card', 'Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'Bank Passbook', 'Proof of occupation'],
    apply_url: 'https://labour.rajasthan.gov.in/'
  }
];